name: advanced_course
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #? Packages
  cupertino_icons: ^1.0.8
  #* State managment
  flutter_bloc: ^8.1.6

  #* Code genetrator (mainly used with cubit and retrofit)
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  #* Dependency injection
  get_it: ^8.0.0
  #* Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  #* Networking.
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.3
  pretty_dio_logger: ^1.4.0
  #* Localizaion.
  intl: ^0.19.0
  easy_localization: ^3.0.7
  #* Splash screen.
  flutter_native_splash: ^2.4.1
  #* An SVG rendering and widget library for Flutter.
  flutter_svg: ^2.0.10+1
  #* Responsive.
  flutter_screenutil: ^5.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
