
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:320502774913:android:f1958396c889580cb9e180",
        firebase_cli_token: "1//09xYCMxqYpIncCgYIARAAGAkSNwF-L9Irc-KP6xA38xS6ci4JZgDEbxnbpfk88s5U1rZMnPoB7u48j1K3hjioIAdssRtHWDob5dk",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "aboameerah2@gmail.com",
        release_notes: "First Fastlane Firebase Distribution!"
  )
  end
end